name: ttct_flutter_full
description: UI Toolkit for the {{#pascalCase}}{{project_name}}{{/pascalCase}} Flutter Application
publish_to: none

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_pretty_dio_logger: ^3.0.0
  get_it: ^7.7.0
  go_router: ^14.1.4
  intl: ^0.19.0
  easy_localization: ^3.0.7
  logger: ^2.3.0
  flutter_easyloading: ^3.0.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  very_good_analysis: ^2.0.4



flutter:
  assets:
    - assets/translations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic